### ISSUE TITLE
Work is suspended

### ISSUE THREAD

**Issue by ngortheone** [ngortheone/org-rs#22]
I am temporarily suspending the work in this project. Reason - GPL License.
The short story: it is incompatible with Rust's ecosystem which is primarily licensed by MIT and Apache2. 

More details here:

- [HN Thread](https://news.ycombinator.com/item?id=19660349)
- [Opensource StackExchange Post](https://opensource.stackexchange.com/questions/8285/org-rs-can-i-use-mit-apache2-lgpl-license)
- [Reddit thread](https://www.reddit.com/r/rust/comments/bm5rwv/orgrs_legally_possible_relicense_to_lgpl/?st=jvfb8no0&sh=38ada04a)

I have reached out to FSF (FSF holds copyrights on Emacs and orgmode) with a question whether a use of permissive license is possible and I'm waiting for their response.
Until then I am not going to  work on this project.

I will continue accepting contributions though if anybody is willing to put their time in.

**Comment by arhad** [comment]
Apache Foundation [states](https://www.apache.org/licenses/GPL-compatibility.html) that the Apache License 2.0 is absolutely compatible with GPLv3, so combined work is naturally licensed under GPLv3.

So the only matter is to mention used components in a help file (and in "About" dialog if a program has UI). According to the Apache Foundation position:

> We avoid GPLv3 software because **merely linking to it is considered by the GPLv3 authors to create a derivative work.** We want to honor their license. Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. This is an identical issue for both GPLv2 and GPLv3.

So you don't need to even ship Apache-specific NOTICE files in source code because linking to Apache library does not create a derivative work.

The same matter is with MIT because it's permissive as well.

**Comment by arhadthedev** [comment]
Could you attach the answer from FSF into a comment, please? Or at least parts with explanations on license compatibility.

**Comment by ngortheone** [comment]
@arhad I am still waiting for reply for FSF (it's been over a week already).
In the meanwhile I decided to roll forward with GPLv3.

>> Or at least parts with explanations on license compatibility.

This project has all the attributes to be considered a derivative of the GPL licensed elisp code. Without direct permission from FSF to publish it under a different license there is nothing to be done.
