### ISSUE TITLE
Are common org addons planned to be covered?

### ISSUE THREAD

**Issue by hyiltiz** [ngortheone/org-rs#3]
Such as
- org-plus-contrib
- org-pomodoro
- org-pdfview
- org-ref
- org-journal
- org-brain
- org-caldav
- and probably many more

If you plan to cover at least some of the most popular ones, we could open up a poll and link it here so until the parser is ready, we can keep collecting responses, and maybe pick the top 3.

**Comment by ngortheone** [comment]
@hyiltiz the whole purpose of writing a parser is to open Org to the world, so the general answer is yes, I am doing this with all the things in mind.
That being said I can't commit that I will do it because I don't know how my life will look like in a year. But I'd be delighted to have the opportunity to do that. This is a beauty of open source - I someone drops the ball someone else will (hopefully) pick it up.

Check out #1 it looks like there is already a lot of interest.

**Comment by ngortheone** [comment]
Add to #7

**Comment by ngortheone** [comment]
Please refer to [FAQ](https://github.com/org-rs/org-rs/wiki/FAQ)
