### ISSUE TITLE
Breach of the GPL

### ISSUE THREAD

**Issue by bryal** [ngortheone/org-rs#4]
By publishing this project under the MIT license, you're most likely in breach of the GPL copyright of the original org-mode project. I suggest you change license to the GPLv3, both for moral and legal reasons. There is some more info in this HN thread: https://news.ycombinator.com/item?id=19660989

**Comment by ngortheone** [comment]
Thanks for pointing this out. Fixed

**Comment by link2xt** [comment]
Still not clear whether it is GPLv3 or GPLv3+. Headers in source files are needed.

**Comment by ngortheone** [comment]
@link2xt can you clarify? My understanding of licensing questions is quite limited

**Comment by link2xt** [comment]
See https://www.gnu.org/licenses/gpl-howto.en.html

You need to add license notices to source files.

If you want GPLv3 **or later** to be applicable, you need to add the text:

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) **any later version**.

Otherwise it is impossible to understand, whether it is allowed to use your library in GPLv4 programs if/when FSF releases it.

**Comment by ngortheone** [comment]
Thanks, it makes sense now. I will be happy to accept the fix in a form of PR. Otherwise I will fix it in the next couple of days
